'''
exceptions.py: exceptions defined by Potion

Authors
-------

Michael Hucka <mhucka@caltech.edu> -- Caltech Library

Copyright
---------

Copyright (c) 2021 by the California Institute of Technology.  This code is
open-source software released under a 3-clause BSD license.  Please see the
file "LICENSE" for more information.
'''


# Base class.
# .............................................................................
# The base class makes it possible to use a single test to distinguish between
# exceptions generated by Potion and exceptions generated by something else.

class PotionException(Exception):
    '''Base class for Potion exceptions.'''
    pass


# Exception classes.
# .............................................................................

class ServerError(PotionException):
    '''Unrecoverable problem involving interactions with the TIND server.'''
    pass

class PotionError(PotionException):
    '''Unrecoverable problem involving Potion.'''
    pass
